<a href="https://colab.research.google.com/github/shaalu2408-pixel/Python-coding-challenges/blob/main/Shalini_Day1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creation of 1D,2D,3D Arrays

In [ ]:
import numpy as np
arr_1d = np.array([2,4,6,8])         #One dimensional array
print(arr_1d)
print(type(arr_1d))

[2 4 6 8]
<class 'numpy.ndarray'>


In [ ]:
arr_2d = np.array([[12,22],[32,42]])   #Two dimensional array
print(arr_2d)
print(type(arr_2d))

[[12 22]
 [32 42]]
<class 'numpy.ndarray'>


In [ ]:
arr_3d = np.array([[[11,12,13],[14,15,16],[17,18,19]]])    #Three dimensional Array
print(arr_3d)
print(type(arr_3d))


[[[11 12 13]
  [14 15 16]
  [17 18 19]]]
<class 'numpy.ndarray'>


Perform addition, subtraction,multiplication and division

In [ ]:

#Two dimensional Array
print(arr_2d+5)       #addition
print(arr_2d-1)       #subtraction
print(arr_2d*2)       #multiplication
print(arr_2d%2)       #division


[[17 27]
 [37 47]]
[[11 21]
 [31 41]]
[[24 44]
 [64 84]]
[[0 0]
 [0 0]]


Use Functions: mean(), sum(), std(),reshape(),arrange,linspace()

In [ ]:
#one dimensional array
print(np.mean(arr_1d))              #mean
print(np.sum(arr_1d))               #sum
print(np.std(arr_1d))               #std
print(arr_1d.reshape(2,2))          #reshape
print(np.arange(2,9,2))             #arange
print(np.linspace(2,8,4))           #linspace






5.0
20
2.23606797749979
[[2 4]
 [6 8]]
[2 4 6 8]
[2. 4. 6. 8.]


Indices of max and min values


In [ ]:
#Three dimensional Array
print(np.max(arr_3d))             #maximum valve
print(np.min(arr_3d))             #minimum value

19
11
